baseURL = "https://nevilspealer.github.io"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Elkan DND Campaigns"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "A place to hold DND thoughts and ideas"
    github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    version = "0.5.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Open Graph and Twitter Cards settings section
    title = "Hugo Techdoc Theme"
    images = ["og-image.png"]
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]
